
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";


export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-1">
        <section id="terms" className="py-12 md:py-24 bg-gray-50 dark:bg-gray-800/20 px-8 md:px-12">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-foreground mb-8">Términos y Condiciones</h2>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-xl font-semibold">1. Relación contractual</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Las presentes Condiciones de uso (“Condiciones”) regulan el acceso o uso que usted haga, exclusivamente dentro del territorio de la República Dominicana, como persona, de aplicaciones, páginas web, contenido, productos y servicios (los “Servicios”) que pone a su disposición, una sociedad de responsabilidad limitada constituida en la República Dominicana, con domicilio social en calle praderas i, #4 Manoguayabo, Santo Domingo Oeste, debidamente registrada en la Cámara de Comercio y Producción de Santo Domingo con el número de registro mercantil 195526PSD.</p>
                    <p className="font-bold uppercase">USTED DEBERÁ LEER DETENIDAMENTE Y ACEPTAR ESTAS CONDICIONES DETENIDAMENTE ANTES DE ACCEDER O USAR LOS SERVICIOS.</p>
                    <p>Mediante su acceso y uso de los Servicios usted acuerda vincularse jurídicamente por estas Condiciones, que establecen una relación contractual entre usted y TECH-FIN-INVEST GLOBAL GROUP S.R.L. y su e-comerce: SISIApp. Si usted no acepta estas Condiciones, no podrá acceder o usar los Servicios. Estas Condiciones sustituyen expresamente los acuerdos o compromisos previos con usted. TECH-FIN-INVEST GLOBAL GROUP S.R.L y SISIApp podrá poner fin de inmediato a estas Condiciones o cualquiera de los Servicios respecto de usted en caso de que usted incumpla las obligaciones contenidas en las presentes Condiciones o, en general, dejar de ofrecer o denegar el acceso a los Servicios o cualquier parte de ellos.</p>
                    <p>Se podrán aplicar condiciones suplementarias a determinados Servicios, como políticas para un evento, una actividad o una promoción particular, y dichas condiciones suplementarias se le comunicarán en relación con los Servicios aplicables, al momento de usted acceder a tales Servicios. Las condiciones suplementarias se establecen además de las Condiciones, y se considerarán una parte de estas, para los fines de los Servicios aplicables. Las condiciones suplementarias prevalecerán sobre las Condiciones en el caso de conflicto con respecto a los Servicios aplicables.</p>
                    <p>SisiApp podrá modificar las Condiciones relativas a los Servicios cuando lo considere oportuno. Las modificaciones serán efectivas después de su publicación por parte de SisiApp de las citadas Condiciones actualizadas en esta ubicación o las políticas modificadas o condiciones suplementarias sobre el Servicio aplicable. Usted deberá aceptar las modificaciones a las Condiciones para poder continuar accediendo y utilizando los Servicios. La recopilación y el uso que hacemos de la información personal en relación con los Servicios es conforme se dispone en la Política de privacidad de SisiApp, disponible en https://www.SisiApp.com/privacy/notice. SisiApp podrá facilitar a un procesador de reclamaciones o a una aseguradora cualquier información necesaria (incluida su información de contacto) si hubiera quejas, disputas o conflictos, que pudieran incluir un accidente, implicándole a usted y a un tercero y dicha información o dichos datos fueran necesarios para resolver la queja, la disputa o el conflicto.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-xl font-semibold">2. Los Servicios</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Los Servicios constituyen una plataforma de tecnología que permite a los usuarios de la aplicación móvil de SisiApp o páginas web proporcionadas como parte de los Servicios (cada una, una “Aplicación”) podrá organizar y planear el servicios y/o logística con terceros proveedores independientes de dichos servicios, incluidos terceros proveedores y/o logísticos independientes, conforme a un acuerdo con SisiApp o algunos afiliados de SisiApp (“Terceros proveedores”). A no ser que SisiApp lo acepte mediante un contrato separado por escrito con usted, los Servicios se ponen a disposición solo para su uso personal, no comercial. USTED RECONOCE QUE SISIAPP NO PRESTA SERVICIOS DE TRANSPORTE, NI DE LIMPIEZA, PLOMERIA, ELECTRICIDAD, ETCÉTERA……. O DE LOGÍSTICA. NO FUNCIONA COMO UNA EMPRESA DE SERVICIOS VARIOS Y QUE DICHOS SERVICIOS O LOGÍSTICA SE PRESTAN POR TERCEROS CONTRATISTAS INDEPENDIENTES, QUE NO ESTÁN EMPLEADOS POR TECH-FIN-INVEST GLOBAL GROUP S.R.L (SISIAPP) NI POR NINGUNA DE SUS AFILIADOS. EN CONSECUENCIA, SON LOS TERCEROS CONTRATISTAS INDEPENDIENTES LOS RESPONSABLES POR LOS SERVICIOS O LOGÍSTICA QUE PRESTAN.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Licencia.</h4>
                    <p>Sujeto al cumplimiento de estas Condiciones, SisiApp le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable, no transferible para: (i) el acceso y uso de las Aplicaciones en su dispositivo personal solo en relación con su uso de los Servicios; y (ii) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través de los Servicios, en cada caso solo para su uso personal, no comercial. SisiApp y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por el presente.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Restricciones.</h4>
                    <p>Usted no podrá: (i) retirar cualquier nota de derechos de autor, marca registrada u otra nota de propiedad de cualquier parte de los Servicios; (ii) reproducir, modificar, preparar obras derivadas sobre los Servicios, distribuir, licenciar, arrendar, revender, transferir, exhibir públicamente, presentar públicamente, transmitir, retransmitir o explotar de otra forma los Servicios, excepto como se permita expresamente por SisiApp; (iii) descompilar, realizar ingeniería inversa o desmontar los Servicios, excepto como se permita por la ley aplicable; (iv) enlazar, reflejar o enmarcar cualquier parte de los Servicios; (v) causar o lanzar cualquier programa o script con el objeto de extraer, indexar, analizar o de otro modo realizar prospección de datos de cualquier parte de los Servicios o sobrecargar o bloquear indebidamente la operación o funcionalidad de cualquier aspecto de los Servicios; o (vi) intentar obtener un acceso no autorizado o dañar cualquier aspecto de los Servicios o sus sistemas o redes relacionados.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Prestación de los Servicios.</h4>
                    <p>Usted reconoce que partes de los Servicios podrán ponerse a disposición bajo varias marcas u opciones de pedidos de SisiApp asociadas con servicios múltiples o los servicios logísticos, incluidas las marcas de servicios actualmente denominadas según su proveedor oferente. Asimismo, usted reconoce que los Servicios podrán ponerse a disposición bajo dichas marcas u opciones de pedidos por o en relación con: (i) ciertas subsidiarias o afiliados de SisiApp; o (ii) Terceros proveedores independientes, incluidos servicios múltiples de empresas de red de servicios varios, titulares de la licencia o permiso de trabajo técnico.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Servicios y contenido de Terceros.</h4>
                    <p>Los Servicios podrán ponerse a disposición o ser accesibles en relación con contenido de terceros (incluida la publicidad) que SisiApp no controle por tratarse de interacciones individuales de los usuarios a través de las Aplicaciones. Usted reconoce que podrán ser de aplicación diferentes condiciones y políticas de privacidad al uso que haga de dichos servicios. SisiApp no respalda el contenido de terceros y serán estos terceros los responsables de su contenido. Adicionalmente, Apple Inc., Google, Inc., Microsoft Corporation o BlackBerry Limited o sus correspondientes subsidiarias o afiliados internacionales serán terceros beneficiarios en este contrato si usted accede a los Servicios utilizando Aplicaciones desarrolladas para dispositivos móviles con sistema iOS, Android, Microsoft Windows, respectivamente. Estos terceros beneficiarios no son parte de este contrato y no son responsables de la prestación o apoyo de los Servicios de ninguna manera. Su acceso a los Servicios utilizando estos dispositivos se sujeta a las condiciones establecidas en las condiciones de servicio de terceros beneficiarios aplicables.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Titularidad.</h4>
                    <p>Los Servicios y todos los derechos relativos a estos son y permanecerán de la propiedad de SisiApp o de sus licenciantes. Ninguna de estas Condiciones ni su uso de los Servicios le transfieren u otorgan ningún derecho: (i) sobre o en relación con los Servicios, excepto en cuanto a la licencia limitada otorgada anteriormente; o bien (ii) a utilizar o mencionar en cualquier modo a los nombres de empresa, logotipos, nombres de producto y servicio, marcas comerciales o marcas de servicio de SisiApp o de sus licenciantes.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-xl font-semibold">3. Su uso de los Servicios</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">Cuentas de usuario.</h4>
                    <p>Con el fin de usar la mayor parte de los aspectos de los Servicios, usted debe registrarse y mantener activa una cuenta personal de usuario de los Servicios (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años, o tener la mayoría de edad legal en su jurisdicción (si es distinta a los 18 años). El registro de la cuenta le requiere que comunique a SisiApp determinada información personal, como su nombre, dirección, número de teléfono móvil, correo electrónico, entre otros, así como por lo menos un método de pago válido (bien una tarjeta de crédito, cuenta bancaria, o bien un socio de pago aceptado). Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, incluso el tener un método de pago inválido o que haya vencido, podrá resultar en su imposibilidad para acceder y utilizar los Servicios o en la resolución por parte de SisiApp de este Contrato celebrado con usted, lo cual le será oportunamente informado. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta. A menos que SisiApp permita otra cosa por escrito, usted solo puede poseer una Cuenta.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Requisitos y conducta del usuario.</h4>
                    <p>El Servicio no está disponible para el uso de personas menores de 18 años. Usted no podrá autorizar a terceros a utilizar su Cuenta, asimismo no podrá permitir a personas menores de 18 años que reciban servicios de terceros proveedores, a menos que aquellos sean acompañados por usted. No podrá ceder o transferir de otro modo su Cuenta a cualquier otra persona o entidad. Usted acuerda cumplir con todas las leyes aplicables al utilizar los Servicios y solo podrá utilizar los Servicios con fines legítimos. En el uso de los Servicios, no causará estorbos, molestias, incomodidades o daños a la propiedad, tanto al Tercero proveedor como a cualquier otra parte. En algunos casos, se le podrá requerir que facilite un documento de identidad u otro elemento de verificación de identidad para el acceso o uso de los Servicios, y usted acepta que se le podrá denegar el acceso o uso de los Servicios si se niega a facilitar el documento de identidad o el elemento de verificación de identidad.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Mensajes de texto.</h4>
                    <p>Al crear una Cuenta, usted acepta que los Servicios le puedan enviar mensajes de texto informativos (SMS) como parte de la actividad comercial normal de su uso de los Servicios. Usted podrá solicitar la no recepción de mensajes de texto informativos (SMS) de SisiApp en cualquier momento enviando un correo electrónico a support@SisiApp.com indicando que no desea recibir más dichos mensajes, junto con el número de teléfono del dispositivo móvil que recibe los mensajes. Usted reconoce que solicitar la no recepción de mensajes de texto informativos (SMS) podrá afectar al uso que usted haga de los Servicios.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Códigos promocionales.</h4>
                    <p>SisiApp podrá, a su sola discreción, crear códigos promocionales que podrán ser canjeados por crédito de Cuenta u otros elementos o beneficios relacionados con los Servicios o los servicios de un Tercero proveedor, con sujeción a cualquier condición adicional que SisiApp establezca sobre la base de cada código promocional (“Códigos promocionales”). Usted acuerda que los Códigos promocionales: (i) deben usarse para la audiencia y el propósito deseado, y de manera lícita; (ii) no podrán duplicarse, venderse o transferirse de ninguna manera, o ponerse a disposición del público general (tanto si se publican en un foro público como de otra forma), a menos que sea con el permiso de SisiApp; (iii) previo aviso a usted, podrán ser invalidados por SisiApp; (iv) podrán usarse solo conforme a las condiciones específicas que SisiApp establezca para dicho Código promocional; (v) no son válidos como efectivo; y (vi) podrán caducar antes de que usted los utilice por vencimiento de la vigencia, uso ilegal o erróneo. SisiApp retendrá o deducirá el crédito u otros elementos o beneficios obtenidos a través de la utilización de los Códigos promocionales por usted o cualquier otro usuario en el caso de que SisiApp determine que el uso o el canje de los Códigos promocionales fue de modo erróneo, fraudulento, ilegal o infringiendo las condiciones del Código promocional o las presentes Condiciones.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Contenido proporcionado por el Usuario.</h4>
                    <p>SisiApp podrá, a su sola discreción, permitirle cuando considere oportuno, que envíe, cargue, publique o de otro modo ponga a disposición de SisiApp a través de los Servicios contenido e información de texto, audio y/o visual, incluidos comentarios y opiniones relativos a los Servicios, iniciación de peticiones de apoyo, así como presentación de admisiones para competiciones y promociones (“Contenido de usuario”). Todo Contenido de usuario facilitado por usted seguirá siendo de su propiedad. No obstante, al proporcionar Contenido de usuario a SisiApp, usted otorga una licencia mundial, por el máximo tiempo permitido por la ley aplicable, transferible, libre de regalías, con derecho a sublicenciar, usar, copiar, modificar, crear obras derivadas, distribuir, exhibir públicamente, presentar públicamente o de otro modo explotar de cualquier manera dicho Contenido de usuario en todos los formatos y canales de distribución, conocidos ahora o ideados en un futuro (incluidos en relación con los Servicios y el negocio de SisiApp y en sitios y servicios de terceros), sin más aviso o consentimiento de usted y sin requerirse el pago a usted o a cualquier otra persona o entidad. Dicho Contenido será tratado por SisiApp conforme se dispone en la Política de privacidad de SisiApp, disponible en https://www.SisiApp.com/privacy/notice.</p>
                    <p>Usted declara y garantiza que: (i) es el único y exclusivo propietario de todo el Contenido de usuario o que tiene todos los derechos, licencias, consentimientos y permisos necesarios para otorgar a SisiApp la licencia al Contenido de usuario como establecido anteriormente; y (ii) ni el Contenido de usuario ni su presentación, carga, publicación o puesta a disposición de otro modo de dicho Contenido de usuario, ni el uso por parte de SisiApp del Contenido de usuario como está aquí permitido, infringirán, malversarán o violarán la propiedad intelectual o los derechos de propiedad de un tercero o los derechos de publicidad o privacidad o resultarán en la violación de cualquier ley o reglamento aplicable.</p>
                    <p>Usted acuerda no proporcionar Contenido de usuario que sea difamatorio, calumnioso, odioso, violento, obsceno, pornográfico, ilícito o de otro modo ofensivo, tanto si dicho material pueda estar protegido o no por la ley. SisiApp podrá en cualquier momento y por cualquier motivo, sin avisarle previamente, revisar, controlar o eliminar Contenido de usuario, pero sin estar obligada a ello.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Acceso a la red y dispositivos.</h4>
                    <p>Usted es responsable de obtener el acceso a la red de datos necesario para utilizar los Servicios. Podrán aplicarse las tarifas y tasas de datos y mensajes de su red móvil si usted accede o utiliza los Servicios desde un dispositivo inalámbrico y usted será responsable de dichas tarifas y tasas. Usted es responsable de adquirir y actualizar el hardware compatible o los dispositivos necesarios para acceder y utilizar los Servicios y Aplicaciones y cualquier actualización de estos. SisiApp no garantiza que los Servicios, o cualquier parte de estos, funcionen en cualquier hardware o dispositivo particular. Además, los Servicios podrán ser objeto de disfunciones o retrasos inherentes al uso de Internet y de las comunicaciones electrónicas.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-xl font-semibold">4. Pago</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Usted entiende que el uso de los Servicios puede derivar en cargos por los servicios o bienes que reciba de un Tercero proveedor, terceros independientes, o por los servicios de intermediación u otros que reciba de SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o desde el extranjero, según corresponda (los “Cargos”). En caso de realizarse Cargos por cuenta del Tercero proveedor, SisiApp, sus afiliadas o subsidiarias serán éstos (el Tercero proveedor, SisiApp, sus subsidiarias o afiliados) quienes le trasladarán y cobrarán los impuestos aplicables en su jurisdicción o en el extranjero y que apliquen conforme a la Ley. Después que haya recibido los servicios u obtenido los bienes (anteriormente referidos) mediante el uso de los Servicios, SisiApp, como agente de cobro limitado, facilitará el pago de los Cargos e impuestos aplicables en nombre del Tercero proveedor o de SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o en el extranjero, según corresponda. El pago de los Cargos e impuestos (cuando resulten aplicables) de dicha manera se considerará como el pago efectuado directamente por usted al Tercero proveedor, SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o en el extranjero, según corresponda. Los Cargos pagados por usted son definitivos y no reembolsables, a menos que SisiApp determine lo contrario por causas razonables imputables a usted, a los Terceros Proveedores o a cualquier tercero independiente. Usted conserva el derecho de solicitar Cargos más bajos de un Tercero proveedor para los servicios o bienes recibidos por usted de dicho Tercero proveedor en el momento en que reciba dichos servicios o bienes. SisiApp responderá en consecuencia a cualquier solicitud de un Tercero proveedor para modificar los Cargos por un servicio o bien en particular. Los cargos pueden incluir otras cuotas, peajes o recargos aplicables, incluyendo cuotas por solicitud, cuotas o cargos municipales, estatales o nacionales/, cargos por demoras, recargos por reclamos de clientes y/o proveedores de servicios o tarifas de procesamiento por pagos fraccionados, entre otros que sean aplicables. Visite www.SisiApp.com/para obtener más información sobre las tarifas estimadas de su Servicios ofrecidos y/o solicitados en caso en particular.</p>
                    <p>Todos los Cargos son pagaderos inmediatamente y el pago se facilitará por SisiApp utilizando el método de pago preferido indicado en su Cuenta, y después de ello SisiApp le enviará un recibo por correo electrónico. Si se determina que el método de pago de su Cuenta principal ha caducado, es inválido o de otro modo no sirve para cobrarle, usted acepta que SisiApp, como agente de cobro limitado del Tercero proveedor, utilice un método de pago secundario en su Cuenta, si estuviera disponible.</p>
                    <p>Los Cargos correspondientes a los servicios o bienes obtenidos a través del uso de los Servicios, podrán ser objeto de modificación o revisión por parte de SisiApp. Además, usted reconoce y acepta que los Cargos aplicables en determinadas zonas geográficas podrán incrementar sustancialmente durante los periodos de alta demanda. SisiApp le informará previamente acerca de los Cargos que podrán aplicarse y usted será responsable de los Cargos incurridos en su Cuenta. SisiApp podrá, cuando lo considere oportuno, proporcionar a determinados usuarios ofertas promocionales y descuentos que pueden resultar en el cobro de diferentes importes por estos o similares servicios o bienes obtenidos a través del uso de los Servicios, y usted acepta que dichas ofertas promocionales y descuentos, a menos que también se pongan a su disposición, no se tendrán en cuenta en el uso por su parte de los Servicios o los Cargos aplicados a usted. Usted podrá optar por cancelar su solicitud para los servicios o bienes de un Tercero proveedor en cualquier momento antes de la llegada de ese Tercero proveedor, en cuyo caso se le podrá cobrar una tasa de cancelación correspondiente, cuyo monto será previamente informado a usted.</p>
                    <p>Esta estructura de pago está destinada para compensar plenamente al Tercero proveedor por los servicios o bienes proporcionados. Usted reconoce y acuerda que los Cargos pagados, constituyen la única contraprestación por los servicios prestados a usted por el Tercero proveedor, y que ninguna parte de este pago incluye alguna propina o gratificación al Tercero proveedor. Cualquier manifestación por parte de SisiApp (en la página web de SisiApp o en los materiales de marketing de SisiApp) en el sentido de que dar una propina es “voluntario”, “no requerido”o “incluido” en los pagos que realiza para los servicios o bienes proporcionados no pretende sugerir que SisiApp proporciona importes adicionales, aparte de los descritos anteriormente, al Tercero proveedor. Usted entiende y acepta que, usted es libre de proporcionar un pago adicional como gratificación a cualquier Tercero proveedor que le proporcione servicios o bienes obtenidos mediante el Servicios y no tiene obligación de ello. Las gratificaciones son voluntarias. Después de que haya recibido los bienes o servicios obtenidos a través del Servicio, tendrá la oportunidad de calificar su experiencia y dejar comentarios adicionales sobre el Tercero proveedor.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Tarifa de reparación, limpieza o cargos por objetos olvidados.</h4>
                    <p>En caso de que usted, o algún tercero respecto el cual usted sea responsable ocasione algún daño al vehículo o a la propiedad del Tercero proveedor por el uso de los Servicios, y que sobrepasen los daños considerados normales por "el desgaste" y la limpieza necesaria, usted deberá asumir el costo de la reparación por daños o de la limpieza necesaria de los vehículos y las propiedades del Tercero proveedor, (“Reparación o Limpieza”). En el caso de que un Tercero proveedor informe de la necesidad de Reparación o Limpieza, producto de acciones u omisiones respecto de las cuales usted o algún tercero del cual usted sea responsable, usted autoriza expresamente a SisiApp a descontar del método de pago indicado en su Cuenta, los montos que razonablemente correspondan por la reparación o limpieza, los cuales serán previamente informados a usted. Dichos importes, así como aquellos cargos por la devolución de objetos olvidados, se transferirán por SisiApp al correspondiente Tercero proveedor y no son reembolsables.</p>
                    <p>Los valores correspondientes a los cargos que se realicen a Usted, por reparación o limpieza,entre otros, los podrá encontrar en https://www.SisiApp.com y podrán ser actualizados en todo momento porSisiApp.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Objetos Olvidados</h4>
                    <p>Usted reconoce y acepta, que usted será el único responsable en todo momento, mientras utiliza los Servicios, del cuidado y resguardo de sus objetos personales o de algún tercero respecto del cual usted sea responsable.</p>
                    <p>Los valores correspondientes a los cargos que se realicen a Usted, por devolución de objetos olvidados o sustraidos, los podrá encontrar en https://www.SisiApp.com y podrán ser actualizados en todo momento porSisiApp, lo cual será informado en el medio antes indicado.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-5">
                <AccordionTrigger className="text-xl font-semibold">5. Exclusión de garantías; Responsabilidades e Indemnidad.</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">EXCLUSIÓN DE GARANTÍAS.</h4>
                    <p>EN LA MEDIDA EN QUE NO SEA CONTRARIO A LA LEY APLICABLE, LOS SERVICIOS SE PROPORCIONAN “TAL CUAL” Y “COMO ESTÁN DISPONIBLES” SIN QUE SISIAPP OTORGUE GARANTÍA, EXPRESA, IMPLÍCITA O ESTATUTARIA, NO EXPRESAMENTE ESTABLECIDA EN ESTAS CONDICIONES, INCLUIDAS LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN PARTICULAR Y NO VIOLACIÓN. ADEMÁS, SISIAPP NO HACE DECLARACIÓN NI PRESTA GARANTÍA ALGUNA RELATIVA A LA FIABILIDAD, PUNTUALIDAD, CALIDAD, IDONEIDAD O DISPONIBILIDAD DE LOS SERVICIOS O CUALQUIERA DE LOS SERVICIOS O BIENES SOLICITADOS A TRAVÉS DEL USO DE LOS SERVICIOS, O QUE LOS SERVICIOS NO SERÁN INTERRUMPIDOS O ESTARÁN LIBRES DE ERRORES. EN CASO DE DETECTARSE POR PARTE DE SISIAPP ALGÚN ERROR O FALLA RELACIONADO CON LOS SERVICIOS, LE SERÁ INFORMADO A USTED. LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS SERVICIOS PROVEÍDOS POR TERCEROS PROVEEDORES SERÁ DE EXCLUSIVA RESPONSABILIDAD DE ÉSTOS. USTED ACUERDA QUE TODO RIESGO DERIVADO DE SU USO DE LOS SERVICIOS Y CUALQUIER SERVICIO O BIEN SOLICITADO EN RELACIÓN CON AQUELLOS SERÁ ÚNICAMENTE SUYO, EN LA MÁXIMA MEDIDA PERMITIDA PELA LEI APLICABLE.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">RESPONSABILIDADES.</h4>
                    <p>LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS SERVICIOS PRESTADOS POR TERCEROS PROVEEDORES INDEPENDIENTES, SERÁ DE EXCLUSIVA RESPONSABILIDAD DE ÉSTOS.</p>
                    <p>USTED SERÁ EL ÚNICO RESPONSABLE DE TODOS LOS DAÑOS Y RELACIONADOS O DERIVADOS DEL USO NEGLIGENTE DE SU PARTE DE LOS SERVICIOS. EN CONSECUENCIA, USTED SERÁ RESPONSABLE DE CUALQUIER DAÑO, RESPONSABILIDAD O PÉRDIDA QUE DERIVEN DE: (I) SU USO O DEPENDENCIA DE LOS SERVICIOS O SU INCAPACIDAD PARA ACCEDER O UTILIZAR LOS SERVICIOS; O (ii) CUALQUIER TRANSACCIÓN O RELACIÓN ENTRE USTED Y CUALQUIER TERCERO PROVEEDOR. USTED RECONOCE QUE LOS EVENTOS QUE VAYAN MÁS ALLÁ DEL CONTROL RAZONABLE DE SISIAPP PODRÁN CAUSAR RETRASO O FALTA DE EJECUCIÓN. USTED RECONOCE QUE LOS TERCEROS PROVEEDORES INDEPENDIENTES DE TRANSPORTE QUE PRESTEN SERVICIOS DE TRANSPORTE SOLICITADOS A TRAVÉS DE ALGUNAS MARCAS DE PEDIDOS PODRÁN OFRECER SERVICIOS DE COCHE COMPARTIDO O ENTRE PARES (PEER-TO-PEER) Y PUEDE QUE NO DISPONGAN DE LA LICENCIA O DEL PERMISO PROFESIONAL. SALVO QUE SE ACREDITE DOLO O NEGLIGENCIA GRAVE DE PARTE DE SISIAPP Y EN LA MEDIDA QUE NO SEA CONTRARIO A LA LEY APLICABLE.</p>
                    <p>USTED PODRÁ UTILIZAR LOS SERVICIOS DE SISIAPP PARA SOLICITAR Y PLANIFICAR SERVICIOS DE CUALQUIER TIPO, CON TERCEROS PROVEEDORES Y SERÁN LOS TERCEROS PROVEEDORES LOS ÚNICOS RESPONSABLES HACIA USTED EN RELACIÓN CON CUALQUIER SERVICIO DE LOS OFRECIDOS Y  PRESTADO A USTED POR ÉSTOS.  SERA USTED COMO SOLICITANTE (CLIENTE) EL RESPONSABLE DE ESTAR PRESENTE Y ASEGURANDO LA VIGILANCIA DEL PROVEEDOR MIENTRAS PERMANEZA EN SUS INSTALACIONES OFRECIENDO SUS SERVICIOS, POR LO QUE DECLARA QUE LIBERA DE CUALQUIER RESPONSABILIDAD A SISIAPP DE CUALQUIER INCONVENIENTE, ACCIDENTE O SUSTRACCION DE EFECTOS O ARTICULOS DEJADOS EN SU ENTORNO, ASÍ COMO CUALQUIER DAÑO SUFRIDO A SU PERSONA FISICA O A SU PROPIEDAD.</p>
                    <p>LAS LIMITACIONES EN ESTE APARTADO NO PRETENDEN LIMITAR LA RESPONSABILIDAD O ALTERAR SUS DERECHOS COMO CONSUMIDOR QUE NO PUEDAN EXCLUIRSE SEGÚN LA LEY APLICABLE.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">INDEMNIDAD.</h4>
                    <p>USTED ACUERDA MANTENER INDEMNES Y RESPONDER FRENTE A SISIAPP Y SUS CONSEJEROS, DIRECTORES, EMPLEADOS Y AGENTES POR CUALQUIER RECLAMACIÓN, DEMANDA, PÉRDIDA, RESPONSABILIDAD Y GASTO (INCLUIDOS LOS HONORARIOS DE ABOGADOS) QUE DERIVEN DE: (I) SU USO DOLOSO O NEGLIGENTE DE LOS SERVICIOS O SERVICIOS O BIENES OBTENIDOS A TRAVÉS DE SU USO DE LOS SERVICIOS; (II) SU INCUMPLIMIENTO O VIOLACIÓN DE CUALQUIERA DE ESTAS CONDICIONES; (III) EL USO POR PARTE DE SISIAPP DE SU CONTENIDO DE USUARIO; O (IV) SU INFRACCIÓN DE LOS DERECHOS DE CUALQUIER TERCERO, INCLUIDOS TERCEROS PROVEEDORES.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-6">
                <AccordionTrigger className="text-xl font-semibold">6. Legislación aplicable y resolución de controversias.</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>De conformidad con lo establecido en la Ley General de Protección de los Derechos del Consumidor o Usuario, las controversias relacionadas con el incumplimiento o violación, rescisión, ejecucción o el uso del Sitio web, en virtud de la protección al consumidor (“Disputas de Protección al Consumidor”), se regirán por las leyes de la República Dominicana. Las partes podrán, de mutuo acuerdo, someter la Disputas de Protección al Consumidor a los tribunales de la República Dominicana, competentes en la materia.</p>
                    <p>En lo referente a las demás controversias que resulten de las presentes Condiciones o que se relacionen en gran parte con ellas, incluyendo las relativas a su validez, interpretación y exigibilidad (cualquier “Disputa”), las presentes Condiciones se regirán e interpretarán exclusivamente en virtud de la legislación de la República Dominicana.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-7">
                <AccordionTrigger className="text-xl font-semibold">7. Otras disposiciones</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">Reclamaciones por infracción de derechos de autor.</h4>
                    <p>Las reclamaciones por infracción de derechos de autor deberán enviarse al agente designado de SisiApp. En la República Dominicana, Usted podrá ponerse en contacto con la siguiente dirección de correo electrónico: info.consumidor@SisiApp.com</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Notificaciones.</h4>
                    <p>SisiApp podrá notificar por medio de una notificación general en los Servicios, mediante un correo electrónico enviado a su dirección electrónica y/o en su Cuenta de SisiApp o por comunicación escrita enviada a su dirección, según lo dispuesto en su Cuenta. Usted podrá notificar a SisiApp por comunicación escrita a la dirección de SisiApp en Santo Domingo Oeste, Calle Praderas I, #4 Rep. Dominicana o al siguiente correo electrónico: info.consumidor@SisiApp.com</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Disposiciones generales.</h4>
                    <p>Usted no podrá ceder ni transferir estas Condiciones, en todo o en parte, sin el consentimiento previo por escrito de SisiApp. Usted da su aprobación a SisiApp para ceder o transferir estas Condiciones, en todo o en parte, incluido a: (i) una subsidiaria o un afiliado; (ii) un adquirente del capital, del negocio o de los activos de SisiApp; o (iii) un sucesor por fusión. No existe entre usted, SisiApp o cualquier Tercer proveedor una empresa conjunta o relación de socios, empleo o agencia como resultado del contrato entre usted y SisiApp o del uso de los Servicios.</p>
                    <p>Si cualquier disposición de estas Condiciones se considerara ilegal, nula o inexigible, ya sea en su totalidad o en parte, de conformidad con cualquier legislación, dicha disposición o parte de esta se considerará que no forma parte de estas Condiciones, aunque la legalidad, validez y exigibilidad del resto de las disposiciones de estas Condiciones no se verá afectada. En ese caso, las partes deberán reemplazar dicha disposición ilegal, nula o inexigible, en todo o en parte por una disposición legal, válida y exigible que tenga, en la medida de lo posible, un efecto similar al que tenía la disposición ilegal, nula o inexigible, dados los contenidos y el propósito de estas Condiciones. Estas Condiciones constituyen el contrato íntegro y el entendimiento entre las partes en relación con el objeto.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>

            <h2 className="text-3xl font-bold text-foreground mt-16 mb-8">Política de Usuarios</h2>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="policy-item-1">
                <AccordionTrigger className="text-xl font-semibold">1. Política de contenido generado por el usuario</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>SisiApp, incluidas sus subsidiarias y filiales (en conjunto, "SisiApp"), puede, a su entera discreción, permitirle a usted y a otros, incluidos proveedores, clientes, repartidores, consumidores, expedidores, establecimientos comerciales, anunciantes y otras empresas o socios (en cualquier caso, el "Usuario" o "usted") que utilizan las plataformas, las herramientas o los canales de redes sociales de SisiApp para crear, enviar, cargar, publicar, enviar mensajes por email o poner a disposición información y contenido de texto, de audio o visual, incluidos comentarios, reseñas y opiniones relacionados con los Servicios (según se definen en las condiciones aplicables que se encuentran en https://www.SisiApp.com/legal), la iniciación de solicitudes de soporte, la comunicación de los comerciantes con los consumidores y el envío de inscripciones para concursos y promociones ("Contenido generado por el usuario" o CGU) a SisiApp o a los Usuarios. Al utilizar o acceder a los Servicios para proporcionarse, confirma que acepta regirse por estas Condiciones del contenido generado por el usuario ("Condiciones"). Estas Condiciones también pueden estar sujetas a otros acuerdos que tenga con SisiApp o a las condiciones aplicables. LEA ESTAS CONDICIONES DETENIDAMENTE, YA QUE CONSTITUYEN UN ACUERDO LEGAL ENTRE USTED Y SISIAPP. En estas Condiciones se entenderá que las palabras “incluyendo” e “incluso” significan “incluyendo, entre otros/as”.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Función de SisiApp en relación con el contenido generado por el usuario</h4>
                    <p>Usted reconoce que SisiApp es un proveedor de servicios en línea y no un editor de CGU. No obstante, SisiApp puede, sin estar obligado a hacerlo, revisar o supervisar el CGU y puede también, a su entera discreción, negarse a mostrarlo, eliminarlo, editarlo o desactivarlo por cualquier motivo, incluso si SisiApp determina que el CGU puede afectar negativamente a SisiApp o que el CGU infringe estas Condiciones, las Directrices generales de la comunidad, las condiciones de cualquier otro acuerdo que se encuentre en SisiApp.com/legal o que usted tenga con SisiApp, cualquier directriz de creación de CGU u otras directrices o políticas de creación de contenido que SisiApp le proporcione ocasionalmente o cualquier otro código, ley, legislación, licencia, orden (incluyendo órdenes judiciales), ordenanza, regla, normativa o cualquier otro requisito impuesto por una autoridad gSisiAppnamental. SisiApp no recomienda ni aprueba ningún CGU disponible en los Servicios. SisiApp tiene derecho a mostrar cualquier CGU que Usted haya enviado en sus Plataformas de acuerdo con estas Condiciones, y tendrá derecho a combinar dicho CGU con cualquier otro creado por otros Usuarios, así como con cualquier contenido creado por SisiApp.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Licencia del contenido generado por el usuario</h4>
                    <p>El CGU sigue siendo de su propiedad. No obstante, usted concede a SisiApp una licencia mundial, perpetua, irrevocable, transferible, con derecho a conceder sublicencias y libre de regalías para usar, copiar, modificar, crear trabajos derivados, distribuir, mostrar públicamente, ejecutar públicamente y explotar de cualquier otra forma dicho CGU, en todos los formatos y canales de distribución conocidos actualmente y en los que se desarrollen en el futuro (incluso en relación con los Servicios y la actividad de SisiApp y con los servicios y sitios de terceros), sin necesidad de notificárselo ni de solicitar su consentimiento, y sin necesidad de pagarle a usted ni a ninguna otra persona o entidad.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-2">
                <AccordionTrigger className="text-xl font-semibold">2. Declaraciones y garantías</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Usted declara y garantiza que: (i) es el propietario único y exclusivo de todo el CGU o que tiene todos los derechos, licencias, consentimientos y autorizaciones necesarios para otorgar a SisiApp la licencia del CGU tal como se ha establecido anteriormente; (ii) ni el CGU, ni el envío, la carga, la publicación, el envío por email, el envío por mensajes o la puesta a disposición de dicho CGU, ni el uso que haga SisiApp del CGU según lo permitido en el presente documento, infringirá ni supondrá una apropiación indebida o una violación de la propiedad intelectual o los derechos de propiedad de un tercero, ni de derechos de publicidad o privacidad, ni dará lugar a la infracción de ningún código, ley, legislación, licencia, orden (incluidas órdenes judiciales), ordenanza, reglamentación ni de ningún otro requisito aplicable, y (iii) usted asume todos los riesgos (incluidas la precisión y la fiabilidad) asociados con el contenido y no implicará en ningún CGU que SisiApp recomienda o verifica dicho contenido. Al proporcionar CGU o utilizar los Servicios de otro modo, acepta que:</p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li>No hará ni permitirá que se haga nada que pueda afectar negativamente a los Servicios o a SisiApp.</li>
                      <li>No usará los Servicios para causar molestias, problemas o daños a propiedades, como, por ejemplo, usar lenguaje vulgar o acosador, incitar al odio, comportarse de forma abusiva o enviar correo no deseado a ninguna de las partes que usen los Servicios.</li>
                      <li>No aportará CGU que sea inapropiado, abusivo, acosador, profano, amenazante, odioso, ofensivo, vulgar, obsceno, sexualmente explícito, despectivo, difamatorio, o que suponga una infracción, invada la privacidad de otra persona, sea inexacto o razonablemente cuestionable.</li>
                      <li>No proporcionará contenido que no tenga permiso para distribuir libremente, incluida información personal de otra persona.</li>
                      <li>No modificará, adaptará, se apropiará, reproducirá, distribuirá, traducirá, creará trabajos derivados o adaptaciones, mostrará públicamente, venderá, comercializará, incorporará en anuncios ni utilizará de ninguna forma el CGU de otro Usuario, excepto con autorización de SisiApp o del propietario de dicho contenido.</li>
                      <li>No se hará pasar por otra persona ni afirmará o insinuará falsamente que es un empleado o representante de SisiApp, ni que conduce o hace entregas con SisiApp.</li>
                      <li>No intentará obtener contraseñas, información de cuenta u otra información privada de ninguna otra persona que utilice los Servicios, ni intentará hacer phishing para obtener dicha información.</li>
                      <li>No utilizará ningún robot ni ningún rastreador u otro dispositivo o proceso automatizado para acceder a los Servicios, independientemente de la finalidad, ni para copiar ningún material de los Servicios.</li>
                      <li>No intentará utilizar los Servicios en ningún servicio, ni a través de ningún servicio, que no esté controlado o autorizado por SisiApp.</li>
                      <li>No promocionará ningún negocio ni empresa comercial, plataforma de entrega de comida o local, ni utilizará los Servicios con fines comerciales, excepto en relación con su cuenta de SisiApp y de acuerdo con estas Condiciones o las condiciones en línea del establecimiento comercial.</li>
                      <li>No promocionará ni fomentará ninguna actividad prohibida descrita anteriormente.</li>
                    </ul>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-3">
                <AccordionTrigger className="text-xl font-semibold">3. Indemnización</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Usted protegerá, defenderá y eximirá de toda responsabilidad a SisiApp, sus Filiales y sus respectivos directores, ejecutivos, empleados, agentes, sucesores y cesionarios, frente a todas las reclamaciones, daños, pérdidas y gastos (incluidos los honorarios razonables de abogados externos) derivados de cualquier reclamación de terceros que surja o esté relacionada con CGU. Acepta que las disposiciones de esta sección seguirán vigentes tras la cancelación de su cuenta o de estas Condiciones.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-4">
                <AccordionTrigger className="text-xl font-semibold">4. Infracción de las condiciones</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Si usted o alguien que utilice su cuenta de SisiApp infringe estas Condiciones o no subsana una infracción después de recibir una advertencia, SisiApp podrá adoptar medidas en su contra, como revocar el acceso a algunos o todos los Servicios, o cancelar su cuenta. En caso de infracciones graves, SisiApp puede adoptar estas medidas sin avisar previamente. Cuando corresponda, SisiApp le notificará las medidas que adoptará en respuesta a las infracciones de estas normas o al incumplimiento de estas Condiciones.</p>
                    <p>Los servicios específicos de SisiApp pueden publicar reglas adicionales que se apliquen a su conducta en dichos servicios.</p>
                    <p>Queremos que los usuarios y los proveedores tengan acceso a herramientas que los ayuden a mantenerse seguros cuando usen nuestro servicio. Para obtener la asistencia que necesitas en una situación de emergencia, llama al 911 desde la app de SisiApp y compartiremos, siempre que estén disponibles, tu ubicación y otros detalles del viaje con el operador. Le brindaremos ciertos datos, como tu ubicación actual estimada al momento de la llamada, tu nombre y número de teléfono, ID, el punto de partida y destino, entre otros datos de interés oportuno.</p>
                    <p>Tú decides si quieres compartir tu ubicación y otros detalles del viaje con el operador del 911. Puedes desactivar la función Compartir mi ubicación y datos del viaje en la página Datos compartidos con emergencias de la configuración de privacidad.</p>
                    <p>La ubicación compartida con el operador del 911 será la latitud y la longitud que señale el sistema operativo de tu dispositivo en el momento en que realices la llamada. Es posible que no sea exacta, en especial, en ambientes urbanos densamente poblados.</p>
                    <p>Cuando optes por compartir la ubicación y los datos del viaje con un operador del 911, se los transmitiremos a RapidSOS, la empresa que provee la plataforma tecnológica que permite compartir la ubicación y los datos de los dispositivos conectados con los operadores del 911. La plataforma de emergencias de RapidSOS solo está integrada con los operadores del 911 en algunas de las áreas de Estados Unidos donde operamos. Si podemos compartir los detalles de tu viaje con un operador del 911, te lo informaremos en la app de SisiApp antes de que realices la llamada. En algunos casos, el centro de llamadas del 911 y RapidSOS pueden procesar algunos de los datos de ubicación y del viaje, pero no todos. P. ej., tal vez el operador del 911 tenga acceso a la ubicación actual estimada, pero no pueda ver el punto de partida y el destino.</p>
                    <p>Para protegerte, SisiApp conservará los datos del viaje y la ubicación, así como la información de la hora en que llamaste al 911 a través de la app. SisiApp puede conservar esta información mientras así lo permita la ley y, una vez cumplido ese plazo, la eliminará. RapidSOS eliminará los datos y la ubicación que reciba de SisiApp en un plazo de 180 días, pero puede conservar un resumen de los datos, como la cantidad y el número de llamadas que procesa. Todo resumen que conserve RapidSOS será anónimo y no contendrá ningún dato que permita vincular la información a una persona específica. SisiApp y RapidSOS nunca grabarán, escucharán ni transcribirán tus llamadas al 911.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-5">
                <AccordionTrigger className="text-xl font-semibold">5. Política de cero tolerancia</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>SisiApp no tolerará el uso de alcohol o drogas por parte de los prestadores de servicios que usan la aplicación de SisiApp. Si usted considera que su técnico o colaborador podría estar bajo la influencia de las drogas o el alcohol, haga que el colaborador PONGA FIN A SU SERVICIO DE INMEDIATO.</p>
                    <p>Después de que el colaborador haya terminado el servicio, reporte cualquier comentario directamente en la aplicación tocando Ayuda en el menú y seleccione su problema. También puede contactarnos visitando help.SisiApp.com o enviando un correo electrónico a customercomplaints@SisiApp.com.</p>
                    <p>Consulte las Guías comunitarias para conocer más sobre cómo SisiApp hace cumplir esta política.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Pautas para todos nosotros</h4>
                    <p>Todos deben seguir las Pautas de la comunidad de SisiApp, que reflejan los 3 pilares: (1) tratar a todos con respeto; (2) ayudar a mantener seguros a los demás; y (3) cumplir la ley.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Tratar a todos con respeto</h4>
                    <p>Las acciones que realices mientras utilizas la Plataforma e-comerce SisiApp pueden tener un gran impacto en la eficiencia y eficacia de solución de temas en el hogar de los demás. La cortesía es importante. Por ejemplo, intenta siempre llegar a tiempo a brindar tu servicio. También es una buena educación no gritar, insultar ni dar portazos. Y si limpias después de ti mismo (ya sea que lleves la basura a casa o limpies el área después de terminar tu trabajo), contribuirás a garantizar que todos sientan tranquilidad y ofrezcas un servicio agradable. Se espera que ejerzas un buen juicio y te comportes decentemente con otras personas cuando utilices la Plataforma e-comerce SisiApp, tal como lo harías en cualquier lugar público.</p>
                    <p>SisiApp es una empresa antirracista. Nos comprometemos a crear un espacio seguro y acogedor para todos, independientemente de su origen. Recuerde que, cuando interactúa con otros miembros de la comunidad de SisiApp, puede encontrarse con personas que pueden parecer diferentes a usted, pensar de manera diferente o tener orígenes diferentes. Respete esas diferencias. La discriminación basada en la raza o cualquier otra característica protegida por la ley no se tolerará en la plataforma SisiApp Marketplace y puede resultar en la pérdida de acceso a las aplicaciones.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Contacto físico</h4>
                    <p>No toques a desconocidos ni a ninguna persona que hayas conocido mientras usas la plataforma e-comerce SisiApp.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Agresión y mala conducta sexual</h4>
                    <p>Todos valoramos nuestro espacio personal y nuestra privacidad. Está bien hablar con otras personas siempre que se mantenga el respeto, pero no hagas comentarios sobre la apariencia de alguien ni le preguntes si está soltero. Se prohíben las agresiones sexuales y la conducta sexual inapropiada de cualquier tipo. La agresión sexual y la conducta sexual inapropiada se refieren al contacto o comportamiento sexual sin el consentimiento explícito de la otra persona. Se debe respetar el espacio personal y la privacidad.</p>
                    <p>SisiApp tiene una regla de no tener relaciones sexuales, independientemente de si conoces a la persona o si te da su consentimiento.</p>
                    <p>Está prohibido el comportamiento amenazante y/o grosero.</p>
                    <p>No se permite ningún comportamiento agresivo, confrontativo o acosador. No utilice lenguaje, haga gestos ni realice acciones que puedan ser irrespetuosas, discriminatorias, amenazantes o inapropiadas.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Contacto post-servicio</h4>
                    <p>El contacto debe finalizar cuando se complete el servicio solicitado, a menos que sea para devolver o buscar un artículo extraviado. El contacto no deseado (cuando no hay consentimiento mutuo) puede considerarse acoso e incluye, por ejemplo, enviar mensajes de texto, llamar, comunicarse a través de las redes sociales, visitar o intentar visitar a alguien en persona después de que se haya completado un servicio.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-6">
                <AccordionTrigger className="text-xl font-semibold">6. Discriminación</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Siempre debes sentirte seguro y bienvenido. Por eso no toleramos conductas ni comportamientos racistas o discriminatorios. No discrimines a nadie ni te muestres despectivo hacia alguien por sus características como raza, etnia, color de piel, edad, discapacidad, identidad de género, estado civil, embarazo, origen nacional, religión, sexo, orientación sexual, idioma, ubicación geográfica o cualquier otra característica protegida por la ley pertinente.</p>
                    <p>La siguiente lista proporciona ejemplos de comportamiento discriminatorio pero no es exhaustiva.</p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li>Negarse a proporcionar  y/o recibir servicios basándose en características como la raza, etnia, color de piel, edad, discapacidad, identidad de género, estado civil, origen nacional, religión, sexo, orientación sexual, idioma, ubicación geográfica o cualquier otra característica protegida por la ley pertinente.</li>
                      <li>Calificar a otro usuario (de cualquier tipo) en función de estos rasgos.</li>
                      <li>Discriminar en función del destino del cliente o la ubicación de entrega de un usuario de SisiApp. Entendemos lo importante que es adaptar la conducción o la entrega a tu vida, en lugar de lo contrario. No es una violación de estas pautas rechazar un servicio o producto porque no te conviene. Pero no está permitido rechazar o cancelar solicitudes intencionalmente, o usar funciones en la Plataforma e-comenrce SisiApp para evitar recibir solicitudes de servicio o producto, únicamente con el propósito de evitar un trato particular debido a las características de las personas o los agentes que se encuentran en esa área.</li>
                      <li>Utilizar lenguaje discriminatorio, hacer comentarios discriminatorios, vilipendiar o hacer preguntas sobre temas delicados relacionados con el origen nacional, la raza, la etnia o cualquier otro rasgo mencionado anteriormente. No se permite hacer comentarios racistas ni utilizar insultos.</li>
                    </ul>
                    <p>Puede obtener más información sobre la Política de no discriminación de SisiApp aquí . También tenemos una política sobre nuestro compromiso con la accesibilidad para ayudar a aumentar las opciones de Servicios o productos para personas con discapacidades  aquí .</p>
                    <p>Si usted es objeto de discriminación o es testigo de un comportamiento discriminatorio, puede informar el incidente a SisiApp tocando Ayuda en las aplicaciones o visitando help.SisiApp.com para que nuestro equipo de soporte pueda hacer un seguimiento y tomar las medidas adecuadas.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Daños a la propiedad</h4>
                    <p>No se permite dañar la propiedad. Algunos ejemplos incluyen dañar el herramientas o enceres del cliente o proveedor solicitado a través de la Plataforma e-comerce SisiApp, romper o vandalizar propiedad ajena intencionalmente, fumar, dañar las instalaciones de un cliente/Proveedor debido a conductas inapropiadas o por cualquier otro motivo. Si daña la propiedad, usted es responsable del costo de las tarifas de limpieza y reparación, además del desgaste normal. El daño intencional puede resultar en la desactivación de la cuenta.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-7">
                <AccordionTrigger className="text-xl font-semibold">7. Ayúdenos a mantenernos seguros unos a otros</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Trabajamos arduamente todos los días para ayudar a crear experiencias más seguras para todos. Su seguridad y comodidad es nuestra prioridad y motivación. Por eso se redactaron estas normas. Todos tenemos un papel que desempeñar para ayudar a crear un entorno seguro.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Compartir cuenta</h4>
                    <p>No se permite compartir cuentas. Por ejemplo, los proveedores de servicios deben completar todas las partes  y etapas de la reserva de este él mismo, incluida any manipulación después de que el cliente  abra su puerta y hasta la entrega final del servicio al cliente de SisiApp. </p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Personas menores de 18 años</h4>
                    <p>Debes tener 18 años o más para tener una cuenta de SisiApp. Los titulares de cuentas no pueden solicitar un servicio o una entrega para alguien menor de 18 años que no esté acompañado por el titular de la cuenta u otro adulto durante el servicio. Al pedir artículos disponibles para comprar a través de la plataforma, los niños tampoco pueden usar la cuenta de SisiApp de un adulto por sí solos. Estas limitaciones de edad se aplican a menos que nuestras pautas, términos u otras políticas locales indiquen lo contrario.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Clientes adicionales y clientes sin cuenta</h4>
                    <p>Al proveer un servicio en SisiApp, no debe llevar consigo otra persona que no sea usted (excepto si se incluya ayudante en su producto o servicio ofrecido. Ejemplo: “chef con camarero incluido”). Estas pautas se aplican a menos que nuestras pautas, términos u otras políticas locales indiquen lo contrario. El titular de la cuenta es responsable del comportamiento de todo su grupo. Si solicita un servicio o producto para otro adulto, usted es responsable de su comportamiento durante el servicio y su cuenta puede verse afectada y/o desactivarse por las acciones que realice.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Información del Proveedor</h4>
                    <p>Para facilitar la recepción del servicio en cuestión, la plataforma e-comerce SisiApp ofrece a los clientes y usuarios de SisiApp información de identificación sobre los proveedores y prestadores de servicios, incluido su ubicación durante el desplazamiento hacia la ubicación pactada, el ID, la foto de perfil y el nombre. Los proveedores y clientes deben completar los servicios utilizando únicamente los procesos y etapas marcadas y aprobados por SisiApp y sus políticas.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Grabación de vídeo y/o audio</h4>
                    <p>Los Proveedores pueden optar por llevar y utilizar una cámara encima suyo, la cual puede utilizarse para grabar los servicios y proporcionar pruebas a SisiApp, a las fuerzas del orden o a las compañías de seguros en caso de que algo salga mal durante un servicio. Los proveedores y clientes también pueden optar por utilizar sus teléfonos y cámaras para grabar los servicios. Tenga en cuenta lo siguiente:</p>
                    <ul className="list-disc pl-6 space-y-2">
                      <li>En algunos lugares, las leyes y reglamentaciones locales exigen que las personas den su consentimiento para ser grabadas o que se les notifique con antelación sobre la grabación. Consulte las leyes locales para comprender sus responsabilidades.</li>
                      <li>Los usuarios pueden enviar grabaciones a SisiApp a su discreción. SisiApp revisará las grabaciones enviadas y tomará todas las medidas que correspondan de acuerdo con las Normas de la comunidad y los términos de uso de la plataforma.</li>
                      <li>Compartir o transmitir la imagen o una grabación de audio o video de una persona en las redes sociales o en otros lugares públicos digitales o físicos es una violación de nuestras Pautas de la comunidad y puede dar lugar a una mayor investigación por parte de nuestro equipo de seguridad.</li>
                    </ul>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Mantenimiento y conservación adecuados</h4>
                    <p>De conformidad con los términos de sus acuerdos con SisiApp y las regulaciones aplicables, se espera que los proveedores de servicios mantengan sus herramientas en buen estado de funcionamiento. Esto significa mantener sus herramientas de acuerdo con los estándares de seguridad y mantenimiento de la industria, y monitorear y reparar cualquier pieza que sea retirada del mercado por el fabricante de las mismas.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Comportamiento con cuidado y seguridad</h4>
                    <p>Se espera que los proveedores se manejen correctamente en el entorno provisto que haga que los clientes se sientan seguros; incluso si las prácticas del servicio no violan la ley, los informes de conducta inapropiada y/o peligrosa pueden provocar la pérdida del acceso a parte o la totalidad de la Plataforma SisiApp. Obtenga más información sobre nuestra Política de comportamiento  aquí .</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-8">
                <AccordionTrigger className="text-xl font-semibold">8. Emergencias</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>En caso de emergencia o si se encuentra en peligro inmediato, alerte a las autoridades locales o a los servicios de emergencia antes de notificar a SisiApp.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Creando una experiencia positiva para los repartidores y los usuarios de SisiApp</h4>
                    <p>Los proveedores deben tener cuidado de completar correctamente el servicio según lo haya publicado (descrito con todo detalle) para poder ser comprado por sus clientes en SisiApp.</p>
                    <p>Los largos tiempos de duración, los largos tiempos de tardanza, demora en la llegada, puntualidad, el tiempo que tarda el proveedor en iniciar o finalizar el servicio desde que está en la ubicación y se introduce el token de validación, el tiempo en camino para llegar, el tiempo de mientras ejerce el servicio, las largas demoras antes de la aceptación del servicio y las altas tasas de cancelación también, las bajas puntuaciones en nivel de estrellas, todo esto crea una experiencia positiva o negativa para los usuarios de SisiApp .</p>
                    <p>Si las métricas de un comerciante están por debajo del estándar mínimo para su ciudad, se lo informaremos.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-9">
                <AccordionTrigger className="text-xl font-semibold">9. Seguir la ley</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Contamos con estándares basados en leyes y regulaciones aplicables que todos deben cumplir. Por ejemplo, está estrictamente prohibido usar la Plataforma SisiApp para cometer cualquier delito (como transportar drogas, lavar dinero, cometer tráfico de drogas o de personas, o explotar sexualmente a menores) o para violar cualquier otra ley.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Cumplir con todas las leyes</h4>
                    <p>Nos comprometemos a cumplir con todas las leyes aplicables y a ganarnos su confianza, y esperamos que todos los que usan la Plataforma SisiApp hagan su parte y conozcan y respeten las leyes y regulaciones pertinentes, incluidas las leyes de tránsito, así como las normas y regulaciones sobre viviendas, terceros, etc, cuando corresponda. Todas las licencias, permisos y cualquier otro documento legal pertinente requerido para los Proveedores de servicios deben mantenerse actualizados.</p>
                    <p>Para los clientes y usuarios de SisiApp, deje que el proveedor desarrolle su trabajo  en cuanto a modo y forma se publicó. Para los clientes y usuarios de SisiApp, no le pida al proveedor de servicio que se quede a terminar más trabajo fuera de lo estrictamente contratado o comprado en SisiApp ni nada que incurra en lo ilegal o lo amoral u obsceno.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-10">
                <AccordionTrigger className="text-xl font-semibold">10. Fraude</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>El engaño puede debilitar la confianza y también ser peligroso. No está permitido falsificar información intencionalmente ni asumir la identidad de otra persona. Es importante brindar información honesta y precisa al informar incidentes, crear y acceder a sus cuentas de SisiApp, disputar o reclamar cargos o tarifas y solicitar créditos.</p>
                    <p>La actividad fraudulenta también puede incluir, pero no se limita a: aumentar deliberadamente el tiempo del servicio contratado; aceptar solicitudes de servicios o producto sin la intención de completarlo, incluida la provocación de otros usuarios para que cancelen; crear cuentas ficticias o cuentas duplicadas indebidas; solicitar o aceptar intencionalmente servicios o productos fraudulentas o falsificados; afirmar fraudulentamente completar un servicio sin completar enteramente todos los detalles publicados u ofrecidos; acciones destinadas a interrumpir o manipular el funcionamiento normal de la Plataforma SisiApp, incluida la manipulación de la configuración de un teléfono para evitar el funcionamiento adecuado de la plataforma y el sistema GPS; abusar de las promociones y/o no usarlas para el propósito previsto; o disputar cargos por razones fraudulentas o ilegítimas.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-11">
                <AccordionTrigger className="text-xl font-semibold">11. Llamadas en pleno desarrollo del servicio de la plataforma</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Para mejorar la seguridad de cada experiencia, se prohíbe desarrollar actividad o servicio a clientes de la plataforma fuera de la plataforma, por lo que nunca solicites ni aceptes pagos fuera de la plataforma SisiApp. Los clientes y los usuarios de SisiApp no deben pagar servicios o productos en efectivo, y los clientes no deben solicitar servicios a los proveedores fuera de la plataforma SisiApp.</p>
                    <p>Están prohibidas las llamadas en el lugar o recinto mientras se desarrolla un servicio de la plataforma SisiApp, esto puede restrasar y/o mermar la calidad y eficacia del servicio brindado. Esto aplica también para cualquier distracción parecida y relevante durante el desarrollo del servicio.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-12">
                <AccordionTrigger className="text-xl font-semibold">12. Directrices sobre propiedad intelectual</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Nunca utilices la marca registrada o la propiedad intelectual de SisiApp sin permiso. Los proveedores también deben devolver los artículos de la marca SisiApp a SisiApp si pierden el acceso a la plataforma. El uso de artículos no autorizados o de terceros (como carteles, señales o artículos similares que lleven el nombre o la marca registrada de SisiApp) puede confundir a los clientes o usuarios de SisiApp. Si la ley local exige mostrar logotipos de la marca SisiApp, los proveedores solo deben usar logotipos oficiales de la marca SisiApp. Los proveedores y repartidores no deben mostrar artículos de la marca SisiApp cuando no accedan a la plataforma.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="policy-item-13">
                <AccordionTrigger className="text-xl font-semibold">13. Tu opinión es importante</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Si ocurre algo, ya sea bueno o malo, te lo ponemos fácil para que nos lo comuniques. Nuestro equipo mejora continuamente nuestros estándares y, tus comentarios son importantes para mantenerlos vigentes a medida que nuestra tecnología evoluciona. Califica tu experiencia al final de cada Servicio. Y si ocurre algo (como un accidente o mal comportamiento) y quieres informarlo, puedes tocar Ayuda en la aplicación o visitar help.SisiApp.com para que nuestro equipo de soporte pueda hacer un seguimiento. En caso de emergencia o si te encuentras en peligro inmediato, alerta a las autoridades locales o a los servicios de emergencia antes de notificar a SisiApp.</p>
                    <p>SisiApp puede, en ocasiones, permitirle a usted y a otras personas que utilicen la Plataforma SisiApp o las herramientas o canales de redes sociales de SisiApp crear, enviar, cargar, publicar, enviar por correo electrónico, enviar mensajes o, de otro modo, poner a disposición de SisiApp o de los usuarios contenido e información de texto, audio o imagen. Dicha actividad y contenido están sujetos a los Términos de contenido generado por el usuario de SisiApp .</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
