
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";


export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <main className="flex-1">
        <section id="terms" className="py-12 md:py-24 bg-gray-50 dark:bg-gray-800/20 px-8 md:px-12">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-foreground mb-8">Términos y Condiciones</h2>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-xl font-semibold">1. Relación contractual</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Las presentes Condiciones de uso (“Condiciones”) regulan el acceso o uso que usted haga, exclusivamente dentro del territorio de la República Dominicana, como persona, de aplicaciones, páginas web, contenido, productos y servicios (los “Servicios”) que pone a su disposición, una sociedad de responsabilidad limitada constituida en la República Dominicana, con domicilio social en calle praderas i, #4 Manoguayabo, Santo Domingo Oeste, debidamente registrada en la Cámara de Comercio y Producción de Santo Domingo con el número de registro mercantil 195526PSD.</p>
                    <p className="font-bold uppercase">USTED DEBERÁ LEER DETENIDAMENTE Y ACEPTAR ESTAS CONDICIONES DETENIDAMENTE ANTES DE ACCEDER O USAR LOS SERVICIOS.</p>
                    <p>Mediante su acceso y uso de los Servicios usted acuerda vincularse jurídicamente por estas Condiciones, que establecen una relación contractual entre usted y TECH-FIN-INVEST GLOBAL GROUP S.R.L. y su e-comerce: SISIApp. Si usted no acepta estas Condiciones, no podrá acceder o usar los Servicios. Estas Condiciones sustituyen expresamente los acuerdos o compromisos previos con usted. TECH-FIN-INVEST GLOBAL GROUP S.R.L y SISIApp podrá poner fin de inmediato a estas Condiciones o cualquiera de los Servicios respecto de usted en caso de que usted incumpla las obligaciones contenidas en las presentes Condiciones o, en general, dejar de ofrecer o denegar el acceso a los Servicios o cualquier parte de ellos.</p>
                    <p>Se podrán aplicar condiciones suplementarias a determinados Servicios, como políticas para un evento, una actividad o una promoción particular, y dichas condiciones suplementarias se le comunicarán en relación con los Servicios aplicables, al momento de usted acceder a tales Servicios. Las condiciones suplementarias se establecen además de las Condiciones, y se considerarán una parte de estas, para los fines de los Servicios aplicables. Las condiciones suplementarias prevalecerán sobre las Condiciones en el caso de conflicto con respecto a los Servicios aplicables.</p>
                    <p>SisiApp podrá modificar las Condiciones relativas a los Servicios cuando lo considere oportuno. Las modificaciones serán efectivas después de su publicación por parte de SisiApp de las citadas Condiciones actualizadas en esta ubicación o las políticas modificadas o condiciones suplementarias sobre el Servicio aplicable. Usted deberá aceptar las modificaciones a las Condiciones para poder continuar accediendo y utilizando los Servicios. La recopilación y el uso que hacemos de la información personal en relación con los Servicios es conforme se dispone en la Política de privacidad de SisiApp, disponible en https://www.SisiApp.com/privacy/notice. SisiApp podrá facilitar a un procesador de reclamaciones o a una aseguradora cualquier información necesaria (incluida su información de contacto) si hubiera quejas, disputas o conflictos, que pudieran incluir un accidente, implicándole a usted y a un tercero y dicha información o dichos datos fueran necesarios para resolver la queja, la disputa o el conflicto.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-xl font-semibold">2. Los Servicios</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Los Servicios constituyen una plataforma de tecnología que permite a los usuarios de la aplicación móvil de SisiApp o páginas web proporcionadas como parte de los Servicios (cada una, una “Aplicación”) podrá organizar y planear el servicios y/o logística con terceros proveedores independientes de dichos servicios, incluidos terceros proveedores y/o logísticos independientes, conforme a un acuerdo con SisiApp o algunos afiliados de SisiApp (“Terceros proveedores”). A no ser que SisiApp lo acepte mediante un contrato separado por escrito con usted, los Servicios se ponen a disposición solo para su uso personal, no comercial. USTED RECONOCE QUE SISIAPP NO PRESTA SERVICIOS DE TRANSPORTE, NI DE LIMPIEZA, PLOMERIA, ELECTRICIDAD, ETCÉTERA……. O DE LOGÍSTICA. NO FUNCIONA COMO UNA EMPRESA DE SERVICIOS VARIOS Y QUE DICHOS SERVICIOS O LOGÍSTICA SE PRESTAN POR TERCEROS CONTRATISTAS INDEPENDIENTES, QUE NO ESTÁN EMPLEADOS POR TECH-FIN-INVEST GLOBAL GROUP S.R.L (SISIAPP) NI POR NINGUNA DE SUS AFILIADOS. EN CONSECUENCIA, SON LOS TERCEROS CONTRATISTAS INDEPENDIENTES LOS RESPONSABLES POR LOS SERVICIOS O LOGÍSTICA QUE PRESTAN.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Licencia.</h4>
                    <p>Sujeto al cumplimiento de estas Condiciones, SisiApp le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable, no transferible para: (i) el acceso y uso de las Aplicaciones en su dispositivo personal solo en relación con su uso de los Servicios; y (ii) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través de los Servicios, en cada caso solo para su uso personal, no comercial. SisiApp y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por el presente.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Restricciones.</h4>
                    <p>Usted no podrá: (i) retirar cualquier nota de derechos de autor, marca registrada u otra nota de propiedad de cualquier parte de los Servicios; (ii) reproducir, modificar, preparar obras derivadas sobre los Servicios, distribuir, licenciar, arrendar, revender, transferir, exhibir públicamente, presentar públicamente, transmitir, retransmitir o explotar de otra forma los Servicios, excepto como se permita expresamente por SisiApp; (iii) descompilar, realizar ingeniería inversa o desmontar los Servicios, excepto como se permita por la ley aplicable; (iv) enlazar, reflejar o enmarcar cualquier parte de los Servicios; (v) causar o lanzar cualquier programa o script con el objeto de extraer, indexar, analizar o de otro modo realizar prospección de datos de cualquier parte de los Servicios o sobrecargar o bloquear indebidamente la operación o funcionalidad de cualquier aspecto de los Servicios; o (vi) intentar obtener un acceso no autorizado o dañar cualquier aspecto de los Servicios o sus sistemas o redes relacionados.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Prestación de los Servicios.</h4>
                    <p>Usted reconoce que partes de los Servicios podrán ponerse a disposición bajo varias marcas u opciones de pedidos de SisiApp asociadas con servicios múltiples o los servicios logísticos, incluidas las marcas de servicios actualmente denominadas según su proveedor oferente. Asimismo, usted reconoce que los Servicios podrán ponerse a disposición bajo dichas marcas u opciones de pedidos por o en relación con: (i) ciertas subsidiarias o afiliados de SisiApp; o (ii) Terceros proveedores independientes, incluidos servicios múltiples de empresas de red de servicios varios, titulares de la licencia o permiso de trabajo técnico.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Servicios y contenido de Terceros.</h4>
                    <p>Los Servicios podrán ponerse a disposición o ser accesibles en relación con contenido de terceros (incluida la publicidad) que SisiApp no controle por tratarse de interacciones individuales de los usuarios a través de las Aplicaciones. Usted reconoce que podrán ser de aplicación diferentes condiciones y políticas de privacidad al uso que haga de dichos servicios. SisiApp no respalda el contenido de terceros y serán estos terceros los responsables de su contenido. Adicionalmente, Apple Inc., Google, Inc., Microsoft Corporation o BlackBerry Limited o sus correspondientes subsidiarias o afiliados internacionales serán terceros beneficiarios en este contrato si usted accede a los Servicios utilizando Aplicaciones desarrolladas para dispositivos móviles con sistema iOS, Android, Microsoft Windows, respectivamente. Estos terceros beneficiarios no son parte de este contrato y no son responsables de la prestación o apoyo de los Servicios de ninguna manera. Su acceso a los Servicios utilizando estos dispositivos se sujeta a las condiciones establecidas en las condiciones de servicio de terceros beneficiarios aplicables.</p>

                    <h4 className="text-lg font-semibold text-foreground pt-2">Titularidad.</h4>
                    <p>Los Servicios y todos los derechos relativos a estos son y permanecerán de la propiedad de SisiApp o de sus licenciantes. Ninguna de estas Condiciones ni su uso de los Servicios le transfieren u otorgan ningún derecho: (i) sobre o en relación con los Servicios, excepto en cuanto a la licencia limitada otorgada anteriormente; o bien (ii) a utilizar o mencionar en cualquier modo a los nombres de empresa, logotipos, nombres de producto y servicio, marcas comerciales o marcas de servicio de SisiApp o de sus licenciantes.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-xl font-semibold">3. Su uso de los Servicios</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">Cuentas de usuario.</h4>
                    <p>Con el fin de usar la mayor parte de los aspectos de los Servicios, usted debe registrarse y mantener activa una cuenta personal de usuario de los Servicios (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años, o tener la mayoría de edad legal en su jurisdicción (si es distinta a los 18 años). El registro de la cuenta le requiere que comunique a SisiApp determinada información personal, como su nombre, dirección, número de teléfono móvil, correo electrónico, entre otros, así como por lo menos un método de pago válido (bien una tarjeta de crédito, cuenta bancaria, o bien un socio de pago aceptado). Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, incluso el tener un método de pago inválido o que haya vencido, podrá resultar en su imposibilidad para acceder y utilizar los Servicios o en la resolución por parte de SisiApp de este Contrato celebrado con usted, lo cual le será oportunamente informado. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta. A menos que SisiApp permita otra cosa por escrito, usted solo puede poseer una Cuenta.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Requisitos y conducta del usuario.</h4>
                    <p>El Servicio no está disponible para el uso de personas menores de 18 años. Usted no podrá autorizar a terceros a utilizar su Cuenta, asimismo no podrá permitir a personas menores de 18 años que reciban servicios de terceros proveedores, a menos que aquellos sean acompañados por usted. No podrá ceder o transferir de otro modo su Cuenta a cualquier otra persona o entidad. Usted acuerda cumplir con todas las leyes aplicables al utilizar los Servicios y solo podrá utilizar los Servicios con fines legítimos. En el uso de los Servicios, no causará estorbos, molestias, incomodidades o daños a la propiedad, tanto al Tercero proveedor como a cualquier otra parte. En algunos casos, se le podrá requerir que facilite un documento de identidad u otro elemento de verificación de identidad para el acceso o uso de los Servicios, y usted acepta que se le podrá denegar el acceso o uso de los Servicios si se niega a facilitar el documento de identidad o el elemento de verificación de identidad.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Mensajes de texto.</h4>
                    <p>Al crear una Cuenta, usted acepta que los Servicios le puedan enviar mensajes de texto informativos (SMS) como parte de la actividad comercial normal de su uso de los Servicios. Usted podrá solicitar la no recepción de mensajes de texto informativos (SMS) de SisiApp en cualquier momento enviando un correo electrónico a support@SisiApp.com indicando que no desea recibir más dichos mensajes, junto con el número de teléfono del dispositivo móvil que recibe los mensajes. Usted reconoce que solicitar la no recepción de mensajes de texto informativos (SMS) podrá afectar al uso que usted haga de los Servicios.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Códigos promocionales.</h4>
                    <p>SisiApp podrá, a su sola discreción, crear códigos promocionales que podrán ser canjeados por crédito de Cuenta u otros elementos o beneficios relacionados con los Servicios o los servicios de un Tercero proveedor, con sujeción a cualquier condición adicional que SisiApp establezca sobre la base de cada código promocional (“Códigos promocionales”). Usted acuerda que los Códigos promocionales: (i) deben usarse para la audiencia y el propósito deseado, y de manera lícita; (ii) no podrán duplicarse, venderse o transferirse de ninguna manera, o ponerse a disposición del público general (tanto si se publican en un foro público como de otra forma), a menos que sea con el permiso de SisiApp; (iii) previo aviso a usted, podrán ser invalidados por SisiApp; (iv) podrán usarse solo conforme a las condiciones específicas que SisiApp establezca para dicho Código promocional; (v) no son válidos como efectivo; y (vi) podrán caducar antes de que usted los utilice por vencimiento de la vigencia, uso ilegal o erróneo. SisiApp retendrá o deducirá el crédito u otros elementos o beneficios obtenidos a través de la utilización de los Códigos promocionales por usted o cualquier otro usuario en el caso de que SisiApp determine que el uso o el canje de los Códigos promocionales fue de modo erróneo, fraudulento, ilegal o infringiendo las condiciones del Código promocional o las presentes Condiciones.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Contenido proporcionado por el Usuario.</h4>
                    <p>SisiApp podrá, a su sola discreción, permitirle cuando considere oportuno, que envíe, cargue, publique o de otro modo ponga a disposición de SisiApp a través de los Servicios contenido e información de texto, audio y/o visual, incluidos comentarios y opiniones relativos a los Servicios, iniciación de peticiones de apoyo, así como presentación de admisiones para competiciones y promociones (“Contenido de usuario”). Todo Contenido de usuario facilitado por usted seguirá siendo de su propiedad. No obstante, al proporcionar Contenido de usuario a SisiApp, usted otorga una licencia mundial, por el máximo tiempo permitido por la ley aplicable, transferible, libre de regalías, con derecho a sublicenciar, usar, copiar, modificar, crear obras derivadas, distribuir, exhibir públicamente, presentar públicamente o de otro modo explotar de cualquier manera dicho Contenido de usuario en todos los formatos y canales de distribución, conocidos ahora o ideados en un futuro (incluidos en relación con los Servicios y el negocio de SisiApp y en sitios y servicios de terceros), sin más aviso o consentimiento de usted y sin requerirse el pago a usted o a cualquier otra persona o entidad. Dicho Contenido será tratado por SisiApp conforme se dispone en la Política de privacidad de SisiApp, disponible en https://www.SisiApp.com/privacy/notice.</p>
                    <p>Usted declara y garantiza que: (i) es el único y exclusivo propietario de todo el Contenido de usuario o que tiene todos los derechos, licencias, consentimientos y permisos necesarios para otorgar a SisiApp la licencia al Contenido de usuario como establecido anteriormente; y (ii) ni el Contenido de usuario ni su presentación, carga, publicación o puesta a disposición de otro modo de dicho Contenido de usuario, ni el uso por parte de SisiApp del Contenido de usuario como está aquí permitido, infringirán, malversarán o violarán la propiedad intelectual o los derechos de propiedad de un tercero o los derechos de publicidad o privacidad o resultarán en la violación de cualquier ley o reglamento aplicable.</p>
                    <p>Usted acuerda no proporcionar Contenido de usuario que sea difamatorio, calumnioso, odioso, violento, obsceno, pornográfico, ilícito o de otro modo ofensivo, tanto si dicho material pueda estar protegido o no por la ley. SisiApp podrá en cualquier momento y por cualquier motivo, sin avisarle previamente, revisar, controlar o eliminar Contenido de usuario, pero sin estar obligada a ello.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Acceso a la red y dispositivos.</h4>
                    <p>Usted es responsable de obtener el acceso a la red de datos necesario para utilizar los Servicios. Podrán aplicarse las tarifas y tasas de datos y mensajes de su red móvil si usted accede o utiliza los Servicios desde un dispositivo inalámbrico y usted será responsable de dichas tarifas y tasas. Usted es responsable de adquirir y actualizar el hardware compatible o los dispositivos necesarios para acceder y utilizar los Servicios y Aplicaciones y cualquier actualización de estos. SisiApp no garantiza que los Servicios, o cualquier parte de estos, funcionen en cualquier hardware o dispositivo particular. Además, los Servicios podrán ser objeto de disfunciones o retrasos inherentes al uso de Internet y de las comunicaciones electrónicas.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-xl font-semibold">4. Pago</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>Usted entiende que el uso de los Servicios puede derivar en cargos por los servicios o bienes que reciba de un Tercero proveedor, terceros independientes, o por los servicios de intermediación u otros que reciba de SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o desde el extranjero, según corresponda (los “Cargos”). En caso de realizarse Cargos por cuenta del Tercero proveedor, SisiApp, sus afiliadas o subsidiarias serán éstos (el Tercero proveedor, SisiApp, sus subsidiarias o afiliados) quienes le trasladarán y cobrarán los impuestos aplicables en su jurisdicción o en el extranjero y que apliquen conforme a la Ley. Después que haya recibido los servicios u obtenido los bienes (anteriormente referidos) mediante el uso de los Servicios, SisiApp, como agente de cobro limitado, facilitará el pago de los Cargos e impuestos aplicables en nombre del Tercero proveedor o de SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o en el extranjero, según corresponda. El pago de los Cargos e impuestos (cuando resulten aplicables) de dicha manera se considerará como el pago efectuado directamente por usted al Tercero proveedor, SisiApp o las subsidiarias o afiliados de SisiApp en su jurisdicción o en el extranjero, según corresponda. Los Cargos pagados por usted son definitivos y no reembolsables, a menos que SisiApp determine lo contrario por causas razonables imputables a usted, a los Terceros Proveedores o a cualquier tercero independiente. Usted conserva el derecho de solicitar Cargos más bajos de un Tercero proveedor para los servicios o bienes recibidos por usted de dicho Tercero proveedor en el momento en que reciba dichos servicios o bienes. SisiApp responderá en consecuencia a cualquier solicitud de un Tercero proveedor para modificar los Cargos por un servicio o bien en particular. Los cargos pueden incluir otras cuotas, peajes o recargos aplicables, incluyendo cuotas por solicitud, cuotas o cargos municipales, estatales o nacionales/, cargos por demoras, recargos por reclamos de clientes y/o proveedores de servicios o tarifas de procesamiento por pagos fraccionados, entre otros que sean aplicables. Visite www.SisiApp.com/para obtener más información sobre las tarifas estimadas de su Servicios ofrecidos y/o solicitados en caso en particular.</p>
                    <p>Todos los Cargos son pagaderos inmediatamente y el pago se facilitará por SisiApp utilizando el método de pago preferido indicado en su Cuenta, y después de ello SisiApp le enviará un recibo por correo electrónico. Si se determina que el método de pago de su Cuenta principal ha caducado, es inválido o de otro modo no sirve para cobrarle, usted acepta que SisiApp, como agente de cobro limitado del Tercero proveedor, utilice un método de pago secundario en su Cuenta, si estuviera disponible.</p>
                    <p>Los Cargos correspondientes a los servicios o bienes obtenidos a través del uso de los Servicios, podrán ser objeto de modificación o revisión por parte de SisiApp. Además, usted reconoce y acepta que los Cargos aplicables en determinadas zonas geográficas podrán incrementar sustancialmente durante los periodos de alta demanda. SisiApp le informará previamente acerca de los Cargos que podrán aplicarse y usted será responsable de los Cargos incurridos en su Cuenta. SisiApp podrá, cuando lo considere oportuno, proporcionar a determinados usuarios ofertas promocionales y descuentos que pueden resultar en el cobro de diferentes importes por estos o similares servicios o bienes obtenidos a través del uso de los Servicios, y usted acepta que dichas ofertas promocionales y descuentos, a menos que también se pongan a su disposición, no se tendrán en cuenta en el uso por su parte de los Servicios o los Cargos aplicados a usted. Usted podrá optar por cancelar su solicitud para los servicios o bienes de un Tercero proveedor en cualquier momento antes de la llegada de ese Tercero proveedor, en cuyo caso se le podrá cobrar una tasa de cancelación correspondiente, cuyo monto será previamente informado a usted.</p>
                    <p>Esta estructura de pago está destinada para compensar plenamente al Tercero proveedor por los servicios o bienes proporcionados. Usted reconoce y acuerda que los Cargos pagados, constituyen la única contraprestación por los servicios prestados a usted por el Tercero proveedor, y que ninguna parte de este pago incluye alguna propina o gratificación al Tercero proveedor. Cualquier manifestación por parte de SisiApp (en la página web de SisiApp o en los materiales de marketing de SisiApp) en el sentido de que dar una propina es “voluntario”, “no requerido”o “incluido” en los pagos que realiza para los servicios o bienes proporcionados no pretende sugerir que SisiApp proporciona importes adicionales, aparte de los descritos anteriormente, al Tercero proveedor. Usted entiende y acepta que, usted es libre de proporcionar un pago adicional como gratificación a cualquier Tercero proveedor que le proporcione servicios o bienes obtenidos mediante el Servicios y no tiene obligación de ello. Las gratificaciones son voluntarias. Después de que haya recibido los bienes o servicios obtenidos a través del Servicio, tendrá la oportunidad de calificar su experiencia y dejar comentarios adicionales sobre el Tercero proveedor.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Tarifa de reparación, limpieza o cargos por objetos olvidados.</h4>
                    <p>En caso de que usted, o algún tercero respecto el cual usted sea responsable ocasione algún daño al vehículo o a la propiedad del Tercero proveedor por el uso de los Servicios, y que sobrepasen los daños considerados normales por "el desgaste" y la limpieza necesaria, usted deberá asumir el costo de la reparación por daños o de la limpieza necesaria de los vehículos y las propiedades del Tercero proveedor, (“Reparación o Limpieza”). En el caso de que un Tercero proveedor informe de la necesidad de Reparación o Limpieza, producto de acciones u omisiones respecto de las cuales usted o algún tercero del cual usted sea responsable, usted autoriza expresamente a SisiApp a descontar del método de pago indicado en su Cuenta, los montos que razonablemente correspondan por la reparación o limpieza, los cuales serán previamente informados a usted. Dichos importes, así como aquellos cargos por la devolución de objetos olvidados, se transferirán por SisiApp al correspondiente Tercero proveedor y no son reembolsables.</p>
                    <p>Los valores correspondientes a los cargos que se realicen a Usted, por reparación o limpieza,entre otros, los podrá encontrar en https://www.SisiApp.com y podrán ser actualizados en todo momento porSisiApp.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Objetos Olvidados</h4>
                    <p>Usted reconoce y acepta, que usted será el único responsable en todo momento, mientras utiliza los Servicios, del cuidado y resguardo de sus objetos personales o de algún tercero respecto del cual usted sea responsable.</p>
                    <p>Los valores correspondientes a los cargos que se realicen a Usted, por devolución de objetos olvidados o sustraidos, los podrá encontrar en https://www.SisiApp.com y podrán ser actualizados en todo momento porSisiApp, lo cual será informado en el medio antes indicado.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-5">
                <AccordionTrigger className="text-xl font-semibold">5. Exclusión de garantías; Responsabilidades e Indemnidad.</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">EXCLUSIÓN DE GARANTÍAS.</h4>
                    <p>EN LA MEDIDA EN QUE NO SEA CONTRARIO A LA LEY APLICABLE, LOS SERVICIOS SE PROPORCIONAN “TAL CUAL” Y “COMO ESTÁN DISPONIBLES” SIN QUE SISIAPP OTORGUE GARANTÍA, EXPRESA, IMPLÍCITA O ESTATUTARIA, NO EXPRESAMENTE ESTABLECIDA EN ESTAS CONDICIONES, INCLUIDAS LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN PARTICULAR Y NO VIOLACIÓN. ADEMÁS, SISIAPP NO HACE DECLARACIÓN NI PRESTA GARANTÍA ALGUNA RELATIVA A LA FIABILIDAD, PUNTUALIDAD, CALIDAD, IDONEIDAD O DISPONIBILIDAD DE LOS SERVICIOS O CUALQUIERA DE LOS SERVICIOS O BIENES SOLICITADOS A TRAVÉS DEL USO DE LOS SERVICIOS, O QUE LOS SERVICIOS NO SERÁN INTERRUMPIDOS O ESTARÁN LIBRES DE ERRORES. EN CASO DE DETECTARSE POR PARTE DE SISIAPP ALGÚN ERROR O FALLA RELACIONADO CON LOS SERVICIOS, LE SERÁ INFORMADO A USTED. LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS SERVICIOS PROVEÍDOS POR TERCEROS PROVEEDORES SERÁ DE EXCLUSIVA RESPONSABILIDAD DE ÉSTOS. USTED ACUERDA QUE TODO RIESGO DERIVADO DE SU USO DE LOS SERVICIOS Y CUALQUIER SERVICIO O BIEN SOLICITADO EN RELACIÓN CON AQUELLOS SERÁ ÚNICAMENTE SUYO, EN LA MÁXIMA MEDIDA PERMITIDA PELA LEI APLICABLE.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">RESPONSABILIDADES.</h4>
                    <p>LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS SERVICIOS PRESTADOS POR TERCEROS PROVEEDORES INDEPENDIENTES, SERÁ DE EXCLUSIVA RESPONSABILIDAD DE ÉSTOS.</p>
                    <p>USTED SERÁ EL ÚNICO RESPONSABLE DE TODOS LOS DAÑOS Y RELACIONADOS O DERIVADOS DEL USO NEGLIGENTE DE SU PARTE DE LOS SERVICIOS. EN CONSECUENCIA, USTED SERÁ RESPONSABLE DE CUALQUIER DAÑO, RESPONSABILIDAD O PÉRDIDA QUE DERIVEN DE: (I) SU USO O DEPENDENCIA DE LOS SERVICIOS O SU INCAPACIDAD PARA ACCEDER O UTILIZAR LOS SERVICIOS; O (ii) CUALQUIER TRANSACCIÓN O RELACIÓN ENTRE USTED Y CUALQUIER TERCERO PROVEEDOR. USTED RECONOCE QUE LOS EVENTOS QUE VAYAN MÁS ALLÁ DEL CONTROL RAZONABLE DE SISIAPP PODRÁN CAUSAR RETRASO O FALTA DE EJECUCIÓN. USTED RECONOCE QUE LOS TERCEROS PROVEEDORES INDEPENDIENTES DE TRANSPORTE QUE PRESTEN SERVICIOS DE TRANSPORTE SOLICITADOS A TRAVÉS DE ALGUNAS MARCAS DE PEDIDOS PODRÁN OFRECER SERVICIOS DE COCHE COMPARTIDO O ENTRE PARES (PEER-TO-PEER) Y PUEDE QUE NO DISPONGAN DE LA LICENCIA O DEL PERMISO PROFESIONAL. SALVO QUE SE ACREDITE DOLO O NEGLIGENCIA GRAVE DE PARTE DE SISIAPP Y EN LA MEDIDA QUE NO SEA CONTRARIO A LA LEY APLICABLE.</p>
                    <p>USTED PODRÁ UTILIZAR LOS SERVICIOS DE SISIAPP PARA SOLICITAR Y PLANIFICAR SERVICIOS DE CUALQUIER TIPO, CON TERCEROS PROVEEDORES Y SERÁN LOS TERCEROS PROVEEDORES LOS ÚNICOS RESPONSABLES HACIA USTED EN RELACIÓN CON CUALQUIER SERVICIO DE LOS OFRECIDOS Y  PRESTADO A USTED POR ÉSTOS.  SERA USTED COMO SOLICITANTE (CLIENTE) EL RESPONSABLE DE ESTAR PRESENTE Y ASEGURANDO LA VIGILANCIA DEL PROVEEDOR MIENTRAS PERMANEZA EN SUS INSTALACIONES OFRECIENDO SUS SERVICIOS, POR LO QUE DECLARA QUE LIBERA DE CUALQUIER RESPONSABILIDAD A SISIAPP DE CUALQUIER INCONVENIENTE, ACCIDENTE O SUSTRACCION DE EFECTOS O ARTICULOS DEJADOS EN SU ENTORNO, ASÍ COMO CUALQUIER DAÑO SUFRIDO A SU PERSONA FISICA O A SU PROPIEDAD.</p>
                    <p>LAS LIMITACIONES EN ESTE APARTADO NO PRETENDEN LIMITAR LA RESPONSABILIDAD O ALTERAR SUS DERECHOS COMO CONSUMIDOR QUE NO PUEDAN EXCLUIRSE SEGÚN LA LEY APLICABLE.</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">INDEMNIDAD.</h4>
                    <p>USTED ACUERDA MANTENER INDEMNES Y RESPONDER FRENTE A SISIAPP Y SUS CONSEJEROS, DIRECTORES, EMPLEADOS Y AGENTES POR CUALQUIER RECLAMACIÓN, DEMANDA, PÉRDIDA, RESPONSABILIDAD Y GASTO (INCLUIDOS LOS HONORARIOS DE ABOGADOS) QUE DERIVEN DE: (I) SU USO DOLOSO O NEGLIGENTE DE LOS SERVICIOS O SERVICIOS O BIENES OBTENIDOS A TRAVÉS DE SU USO DE LOS SERVICIOS; (II) SU INCUMPLIMIENTO O VIOLACIÓN DE CUALQUIERA DE ESTAS CONDICIONES; (III) EL USO POR PARTE DE SISIAPP DE SU CONTENIDO DE USUARIO; O (IV) SU INFRACCIÓN DE LOS DERECHOS DE CUALQUIER TERCERO, INCLUIDOS TERCEROS PROVEEDORES.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-6">
                <AccordionTrigger className="text-xl font-semibold">6. Legislación aplicable y resolución de controversias.</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <p>De conformidad con lo establecido en la Ley General de Protección de los Derechos del Consumidor o Usuario, las controversias relacionadas con el incumplimiento o violación, rescisión, ejecucción o el uso del Sitio web, en virtud de la protección al consumidor (“Disputas de Protección al Consumidor”), se regirán por las leyes de la República Dominicana. Las partes podrán, de mutuo acuerdo, someter la Disputas de Protección al Consumidor a los tribunales de la República Dominicana, competentes en la materia.</p>
                    <p>En lo referente a las demás controversias que resulten de las presentes Condiciones o que se relacionen en gran parte con ellas, incluyendo las relativas a su validez, interpretación y exigibilidad (cualquier “Disputa”), las presentes Condiciones se regirán e interpretarán exclusivamente en virtud de la legislación de la República Dominicana.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-7">
                <AccordionTrigger className="text-xl font-semibold">7. Otras disposiciones</AccordionTrigger>
                <AccordionContent>
                  <div className="text-muted-foreground space-y-4 text-justify pt-4">
                    <h4 className="text-lg font-semibold text-foreground pt-2">Reclamaciones por infracción de derechos de autor.</h4>
                    <p>Las reclamaciones por infracción de derechos de autor deberán enviarse al agente designado de SisiApp. En la República Dominicana, Usted podrá ponerse en contacto con la siguiente dirección de correo electrónico: info.consumidor@SisiApp.com</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Notificaciones.</h4>
                    <p>SisiApp podrá notificar por medio de una notificación general en los Servicios, mediante un correo electrónico enviado a su dirección electrónica y/o en su Cuenta de SisiApp o por comunicación escrita enviada a su dirección, según lo dispuesto en su Cuenta. Usted podrá notificar a SisiApp por comunicación escrita a la dirección de SisiApp en Santo Domingo Oeste, Calle Praderas I, #4 Rep. Dominicana o al siguiente correo electrónico: info.consumidor@SisiApp.com</p>
                    <h4 className="text-lg font-semibold text-foreground pt-2">Disposiciones generales.</h4>
                    <p>Usted no podrá ceder ni transferir estas Condiciones, en todo o en parte, sin el consentimiento previo por escrito de SisiApp. Usted da su aprobación a SisiApp para ceder o transferir estas Condiciones, en todo o en parte, incluido a: (i) una subsidiaria o un afiliado; (ii) un adquirente del capital, del negocio o de los activos de SisiApp; o (iii) un sucesor por fusión. No existe entre usted, SisiApp o cualquier Tercer proveedor una empresa conjunta o relación de socios, empleo o agencia como resultado del contrato entre usted y SisiApp o del uso de los Servicios.</p>
                    <p>Si cualquier disposición de estas Condiciones se considerara ilegal, nula o inexigible, ya sea en su totalidad o en parte, de conformidad con cualquier legislación, dicha disposición o parte de esta se considerará que no forma parte de estas Condiciones, aunque la legalidad, validez y exigibilidad del resto de las disposiciones de estas Condiciones no se verá afectada. En ese caso, las partes deberán reemplazar dicha disposición ilegal, nula o inexigible, en todo o en parte por una disposición legal, válida y exigible que tenga, en la medida de lo posible, un efecto similar al que tenía la disposición ilegal, nula o inexigible, dados los contenidos y el propósito de estas Condiciones. Estas Condiciones constituyen el contrato íntegro y el entendimiento entre las partes en relación con el objeto.</p>
                  </div>
                </AccordionContent>
              </AccordionItem>
            </Accordion>

            <h2 className="text-3xl font-bold text-foreground mt-16 mb-8">Política de Usuarios</h2>
            <div className="text-muted-foreground space-y-4 text-justify">
              <p>Contenido provisional para la política de usuarios.</p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
